# Generated by Django 4.2.7 on 2024-01-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_news', '0003_savedvocab'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
                ('nickname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSavedArticle',
            fields=[
                ('pk_column', models.AutoField(primary_key=True, serialize=False)),
                ('article_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_saved_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSavedWord',
            fields=[
                ('pk_column', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_saved_word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YesasiaArticletitle',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('is_read', models.IntegerField(blank=True, null=True)),
                ('update_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yesasia_articletitle',
                'managed': False,
            },
        ),
    ]
