# Generated by Django 4.2.7 on 2023-12-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVocab',
            fields=[
                ('vocab_id', models.AutoField(primary_key=True, serialize=False)),
                ('canonical_form', models.TextField(blank=True, null=True)),
                ('saved_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saved_vocab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordCanonical',
            fields=[
                ('canonical_id', models.AutoField(primary_key=True, serialize=False)),
                ('canonical_form', models.TextField(blank=True, null=True)),
                ('pos', models.TextField(blank=True, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('verb_aspect', models.TextField(blank=True, null=True)),
                ('imperfective_perfective', models.TextField(blank=True, null=True)),
                ('is_saved', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'word_canonical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordDeclension',
            fields=[
                ('declension_id', models.AutoField(primary_key=True, serialize=False)),
                ('form', models.TextField(blank=True, null=True)),
                ('clean_form', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'word_declension',
                'managed': False,
            },
        ),
    ]
