# Generated by Django 4.2.7 on 2023-12-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YandexArticletitle',
            fields=[
                ('article_id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('is_read', models.IntegerField(blank=True, null=True)),
                ('update_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yandex_articletitle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YesasiaArticletitle',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('is_read', models.IntegerField(blank=True, null=True)),
                ('update_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yesasia_articletitle',
                'managed': False,
            },
        ),
    ]
