# Generated by Django 4.2.7 on 2023-12-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yesasia', '0002_wordcanonical_worddeclension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVocab',
            fields=[
                ('vocab_id', models.AutoField(primary_key=True, serialize=False)),
                ('canonical_form', models.TextField(blank=True, null=True)),
                ('saved_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saved_vocab',
                'managed': False,
            },
        ),
    ]
